Добавил код с лекций и свойство квадрату для разрешения проблемы.
Arity-T/1_figures pull request #2
Opened 2024-11-03 18:22 UTC by vlgUseless

2024-11-06 16:37 UTC, Arity-T approved these changes, later dismissed
Обязательных правок нет, но есть комментарии по некоторым тонким моментам. Я апрувлю, там смотри сам, можешь просто вмёрджить, можешь что-то поменять, если есть время и желание разбираться с питонячими особенностями.

2024-11-06 16:37 UTC, Arity-T commented on figures/figures.py
> +        self.__x = x
Ммм... С двумя подчёркиваниями в python не всё прямо-таки однозначно. Это не совсем про привычные в C++ private variables, в python таких вообще не существует, доступ к ним всё равно можно получить вот так `shape_obj._Shape__x`. Это называется `Name mangling` и сделано не для заперта доступа, он всё равно есть, а для предотврощения случайного доступа. private переменные в python лучше просто делать с одним подчёркиванием, это более привычное соглашение, а по умолчанию, если нет уверенности в том, что переменная должна-должна быть private, то и не её делать private, это будет наиболее по питоновски :)

2024-11-06 16:37 UTC, Arity-T commented on figures/figures.py
> +        self.__x = x
Ну и если про наш конкретный случай. Кажется, как будто в дочерних классах могут понадобится координаты. Более того, они могут понадобится и когда ты извне используешь пакет и эти классы. Сейчас вроде как напрямую нельзя (условно запретил разработчик библиотеки), геттеров и сеттеров нету, но при ините мы их задаём. Зачем тогда вообще их задавать? Если ни записать (но это ладно, допустим константные координаты почему-то), ни прочитать их потом нельзя, только в виде строчки через repr получить (а потом парсить?)

2024-11-06 16:37 UTC, Arity-T commented on figures/figures.py
> +            f"{Shape.__repr__(self)}, со сторонами {self.width} и {self.height},"
К родительскому классу лучше обращаться не напрямую, а через `super()`

2024-11-06 16:37 UTC, Arity-T commented on figures/figures.py
> +        return f"{self.name} по координатам ({self.__x}, {self.__y})"
По смыслу это `__str__`, а не `__repr__` :) Почитать можно где-нибудь на [stack overflow](https://stackoverflow.com/questions/1436703/what-is-the-difference-between-str-and-repr)

2024-11-06 16:37 UTC, Arity-T commented on figures/figures.py
> +            f"{Shape.__repr__(self)}, со стороной {self.width},"
Хм, __repr__ от Shape тут участвует, а __repr__ от __Rectangle__ нет, и дублирование кода от того тоже появляется

2024-11-06 16:49 UTC, vlgUseless commented
Это один в один код с лекции, на которой демонстрировался пример нарушения принципа подстановки. Я могу подправить эти моменты, но подразумевается ли это заданием?) Сам файл в репозитории: https://github.com/polytech-lectures-python/lecture-6-oop/blob/master/1_basics/inheritance_and_polymorphism.py
От меня было добавлено только свойство квадрату в виде стороны (side).

2024-11-07 07:53 UTC, vlgUseless commented
Вроде как изменил всё, перепроверьте ещё раз.

2024-11-07 08:02 UTC, vlgUseless commented
Странная ситуация с __str__ классов Rectangle и Square, поскольку нормально переиспользовать __str__ от Rectangle мы не можем, так как там выводятся две стороны, а в Square одна.
Приходится вот так вызывать __str__ класса Shape. Не знаю, насколько это правильно, но хороших идей больше не вижу.

2024-11-07 09:47 UTC, Arity-T requested changes

2024-11-07 09:47 UTC, Arity-T commented on figures/figures.py
> +            f"{super(Shape, self).__str__()}, со стороной {self.side},"
Ошибочка `super(Shape, self)` -> `super(Rectangle, self)`
super ищет методы начиная с указанного класса **невключительно**, то есть тут  `super(Rectangle, self)` поиск будет начиная со следующего класса в MRU (method resolution order, подробнее например [тут](https://aran-fey.github.io/programming-guides/super.html)).
В данном случае метод __str__ не находится и вызывается __repr__ квадрата (можешь сам запустить и убедиться)

2024-11-07 09:47 UTC, Arity-T commented on .pylintrc
> +ignore=venv, build, dist
Это какие-то PyCharmные штуки?

2024-11-07 10:11 UTC, vlgUseless commented on .pylintrc
> +ignore=venv, build, dist
По логике не обязательно PyCharm-ные, но они у меня откуда-то взялись и при использовании линтера он находит исходные файлы и файлы в built (которые одни и те же) и ругается, что код дублируется.
Вообще build у нас в .gitignore.

2024-11-07 10:12 UTC, vlgUseless commented on figures/figures.py
> +            f"{super(Shape, self).__str__()}, со стороной {self.side},"
Понял и исправил, великий язык.

2024-11-07 18:43 UTC, Arity-T submitted a review, later dismissed

2024-11-13 07:36 UTC, Arity-T approved these changes
Ну, конечно, вот эта конструкция `super(Rectangle, self).__str__()` мне не нравится, вернее с ней-то нет ничего плохого, просто само использования `__str__` деда это странно, но раз уж в лекции так, то ладно, задача не в том, чтобы код с лекции править.

По идее в текущей реализации, всё ок с LSP.

2024-11-13 07:37 UTC, merged